### PR TITLE
Add dormant investment status

### PR DESCRIPTION
**Pull request by ztolley**
Adds an option to the investment status form and the filter.

### CODE REVIEW

**Comment by feedmypixel** [comment]
any tests around this work?

**Comment by ztolley** [comment]
There are none around the existing status change form, I was waiting for the base set of collection tests before going and writing one. For this change we just add another option

**Comment by feedmypixel** [comment]
> There are none around the existing status change form, I was waiting for the base set of collection tests before going and writing one. For this change we just add another option

sorry I meant unit tests

**Comment by feedmypixel** [comment]
Ok we don't have any tests around metadata!

Also how come this is in metadata like this? feels like this should be in the backend?

**Comment by ztolley** [comment]
The test would just say does the metadata have a list of options that include this, so not really a test of logic and there are no tests in metadata right now.

This will get moved to the backend soon but it seems that isn't going to happen before launch.

**Comment by feedmypixel** [comment]
Can you add a `TODO` please that this will be moved to the backend? I don't want future devs to see this and just copy and paste the example. Really it shouldn't be in here in the first place.

**Comment by ztolley** [comment]
https://uktrade.atlassian.net/browse/DH-1170

**Comment by feedmypixel** [comment]
Grudgingly approved - we really shouldn't be adding things in to the frontend as a "quick" way of doing things. This should be in the backend like all the other things in this file...

It really is a false economy in the long run

**Pull request merged**
