### PR TITLE
Moved ActivityFeed components from data-hub-components (Firebreak week)

### PR DESCRIPTION
**Pull request by ambrozic**
## Description of change

To be able to display new types of activities in activity feed we had to move activity feed components from `data-hub-components` to this repo. This is initial work just to move activity feed components so we can add new ones later.

## Test instructions

_What should I see?_

### Before

_Add a screenshot_

### After

_Add a screenshot_

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

### CODE REVIEW

**Comment by paulgain** [comment]
@ambrozic I think it's best to create two PRs. One for the move and the second for the changes.

**Comment by ambrozic** [comment]
> @ambrozic I think it's best to create two PRs. One for the move and the second for the changes.

right now i need it like this so we can demo changes to activity feed. i will separate changes in two pull requests afterwards.

**Review by paulgain — APPROVED** [review]
Despite the size of this PR there are only 6 one-liner changes. I've checkout out this branch and loaded various companies that have lots of activity - LGTM 👍

**Comment by paulgain** [comment]
@ambrozic I've just noticed you've brought over this [file](https://github.com/uktrade/data-hub-frontend/blob/activity-feed-components/src/client/components/ActivityFeed/utils.js). The contents of this file now live [here](https://github.com/uktrade/data-hub-frontend/blob/activity-feed-components/src/client/utils/date-utils.js) and [here](https://github.com/uktrade/data-hub-frontend/blob/activity-feed-components/src/client/utils/number-utils.js). If the Activity Feed has a dependency on your [file](https://github.com/uktrade/data-hub-frontend/blob/activity-feed-components/src/client/components/ActivityFeed/utils.js) I would refactor the file out for the new ones. You can either create a separate PR for this work or include a second commit - whatever you prefer.

**Comment by ambrozic** [comment]
@paulgain this is bothering me as well. i will refactor it in this PR.

**Comment by ambrozic** [comment]
@paulgain refactored DateUtils and NumberUtils

**Comment by paulgain** [comment]
@ambrozic the refactoring LGTM 👍

**Review by LaurenQurashi — APPROVED** [review]

**Comment by paulgain** [comment]
@LaurenQurashi @ambrozic

Unfortunately, we can't merge this PR as it now contains both the Activity Feed migration and the Firebreak week experimental code, all as a single commit - not sure what's happened here but we can't merge this into `master`. 

The PR is also missing Activity Feed dependencies, these dependencies were defined in the `data-hub-component` library.
In addition, this PR still pulls in the `data-hub-component` library which we need to drop. 

It's cleaner if we create a [new PR](#3041 ) and **simply pull in the component library and drop the data-hub-component dependency - that's it!**.

Let's not close this PR as there are valuable learnings to be had from the Firebreak week. Thanks.

**Pull request closed without merging**
