### PR TITLE
Added the /api proxy endpoint

### PR DESCRIPTION
**Pull request by peterhudec**
## Description of change

Added the `/api` endpoint, which proxies all requests to `config.apiRoot` with added `authorization: Bearer <session.token>` header. The `/api` prefix is stripped from the requests e.g a request to `localhost:3000/api/v4/company-list` will be proxied to `<apiRoot>/v4/company-list`.

## Test instructions

* You should be able to access the API from `/api` without the need to use the access token.
* You should not be able to access the API from `/api` if you are not logged in.

- [ x] Has the branch been rebased to develop?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

### CODE REVIEW

**Comment by rafenden** [comment]
This potentially might expose some data we don't want to be publicly accessible, could some BE devs have a look as well? @alixedi @currycoder @reupen @elcct

**Comment by reupen** [comment]
I think, if we do this, we may want a whitelist of URL paths. E.g. we shouldn't expose `/admin/` through this.

**Comment by peterhudec** [comment]
It turned out that there already is an `/api` endpoint, only accomodating `/api/options` and `api/postcodelookup`. I tried to move them to `/options` and `/postcodelookup`, but the tests are so tightly coupled to the folder structure with _proxyquire_ that I gave upa and just renamed my new endpoint to `/api-proxy`.

**Comment by mcbhenwood** [comment]
We should resurrect this PR really.

I think the approach is sound but we also need a way to stop this leaking API endpoints. How about something like this:

- This endpoint adds an HTTP header to the API request, something like `X-Http-Datahub-Proxy-Version: 1`
- Create a decorator for API View methods, something like `@AllowFrontendProxiedCall`
- Add some middleware which rejects requests which contain that header but which are directed to views not wrapped in that decorator

That way you can switch on the backend methods one by one and by default they are off.

**Pull request closed without merging**
