### PR TITLE
upgrade cf buildpacks and node version

### PR DESCRIPTION
**Pull request by nusnewob**

### CODE REVIEW

**Comment by feedmypixel** [comment]
@nusnewob you also need to update the node versions here:
https://github.com/uktrade/data-hub-frontend/blob/develop/.circleci/config.yml#L5
https://github.com/uktrade/data-hub-frontend/blob/develop/.circleci/config.yml#L20
https://github.com/uktrade/data-hub-frontend/blob/develop/.circleci/config.yml#L40

**Comment by ztolley** [comment]
How long till 8.7.0 gets added to the build packs?

**Comment by jim68000** [comment]
Getting from 8.5 to 8.6 took about two weeks, so we'll do this again in a fortnight

**Comment by feedmypixel** [comment]
@nusnewob whats going on with this PR?

**Pull request closed without merging**
