### PR TITLE
Feature/uk postcode

### PR DESCRIPTION
**Pull request by peterhudec**
## Description of change

Added the _UK postcode_ filter to _companies_ page.

## Test instructions

Note, that the feature depends on the uktrade/data-hub-api#2441 PR.

1. Go to [`/companies`](https://data-hub-frontend-dev-pr-2358.herokuapp.com/companies?sortby=modified_on%3Adesc&archived=false)
2. In the sidebar, right underneath the _Country_ filter you should see the _Uk postcode_ filter.
3. The filter should conform to the specification
4. Enter a postcode (even an incomplete one) or multiple coma-separated list of postcodes to the filter
5. Blur the input field, or hit enter
6. The search results should now only show companies with the postcodes you entered
 
### Before
Screen Shot 2020-01-10 at 2 34 17 PM

### After 
Screen Shot 2020-01-10 at 2 34 03 PM

## Checklist

- [x] Has the branch been rebased to develop?
- [x] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

### CODE REVIEW

**Comment by mforner13** [comment]
@peterhudec I'm not sure if this is something we should provision against, but if I enter one or multiple postcodes, and then put a comma after the last one (E.g.: NE28, IG6, ) I get an error page. 
Screenshot 2020-01-13 at 09 33 35

**Comment by peterhudec** [comment]
@mforner13 the bug with the trailing commas is now fixed.

**Comment by mforner13** [comment]
> @mforner13 the bug with the trailing commas is now fixed.

Looks good @peterhudec !

If I put a space after the comma, it still throws the error as it's not caught by the boolean filter - E.g: 'NE28, ' - although I know it's not very common behaviour so not sure if it's a problem.

**Comment by peterhudec** [comment]
@mforner13 the space bug is fixed now.

**Pull request merged**
