### PR TITLE
Remove crest

### PR DESCRIPTION
**Pull request by ztolley**
Removes the crest from the top masthead as requested.

nocrest

snip 2
snip3

### CODE REVIEW

**Comment by teneightfive** [comment]
That badge doesn't look aligned properly any more.

**Comment by feedmypixel** [comment]
@ztolley I didn't think the crest was being removed?

**Comment by ztolley** [comment]
Yup.. the card was descoped back to 2 things, remove the crest and change alpha to beta

**Comment by ztolley** [comment]
@teneightfive I look at the current alignment and fix that, and I noticed the left align on the word data hub is also off.

**Comment by ztolley** [comment]
@teneightfive Adjusted the position of the phase badge to compensate for lack of crest image. Added 2 images to show before and after (left and right padding, this simply down to how the image was cropped)

**Comment by teneightfive** [comment]
😢

**Pull request merged**
