### PR TITLE
Remove interactions nav and search

### PR DESCRIPTION
**Pull request by ztolley**
Interactions should only be visible within the context of a contact, company or investment project, not from the top level navigation or search results.

* Removed interactions from top-level nav
* Removed interactions tab from search
* Removed code related to interaction lists no longer used
* Removed tests no longer used

### CODE REVIEW

**Comment by tyom** [comment]
Could we use this sub-app for embedding it into other apps rather than completely removing?

**Comment by ztolley** [comment]
The common code that is used for company/contact/investment views remains and is not removed, this is just to remove the code for the top level view and remove the nav tabs

**Comment by tyom** [comment]
This breaks the breadcrumb and `/interactions` URL. Do we have a plan on how we're going to support those?

**Comment by ztolley** [comment]
The point is we remove the /interactions endpoint. but if this is a link in the breadcrumb I need to correct that

**Pull request closed without merging**
