### PR TITLE
chore: update webpack to fix broken storybook startup

### PR DESCRIPTION
**Pull request by debitan**
## Description of change

Update webpack and related dependencies to fix following storybook error:

```
10% building 1/1 modules 0 active(node:11438) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
(node:11438) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createSnapshot' of undefined
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:13:36
    at new Promise (<anonymous>)
    at Object.createSnapshot (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/html-webpack-plugin/lib/webpack5/file-watcher-api.js:12:10)
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/html-webpack-plugin/lib/cached-child-compiler.js:219:35
(node:11438) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:11438) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17
                compilation.templatesPlugin("render-with-entry", (source, chunk, hash) => {
                            ^
TypeError: compilation.templatesPlugin is not a function
    at SetVarMainTemplatePlugin.apply (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/webpack/lib/SetVarMainTemplatePlugin.js:17:15)
    at Compilation.apply (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/tapable/lib/Tapable.js:79:16)
    at Compilation.deprecated [as apply] (internal/util.js:89:15)
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/webpack/lib/LibraryTemplatePlugin.js:45:18
    at SyncHook.eval [as call] (eval at create (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
    at SyncHook.lazyCompileHook (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/tapable/lib/Hook.js:154:20)
    at Compiler.newCompilation (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:630:30)
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/@storybook/core/node_modules/webpack/lib/Compiler.js:667:29
    at eval (eval at create (/Users/davidmatthews/code/DIT/datahub-front-end/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/@storybook/core/node_modules/webpack/lib/DllReferencePlugin.js:72:15
    at /Users/davidmatthews/code/DIT/datahub-front-end/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! data-hub-frontend@ storybook: `start-storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the data-hub-frontend@ storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidmatthews/.npm/_logs/2020-07-16T14_46_42_405Z-debug.log
```

There is more work to do in this area. According to the [v3 -> v4 migration guide](https://webpack.js.org/migrate/4/), e.g. we still need to set the mode (this warning appears in the console when running the site). 

However, I believe these can be addressed in future PRs. This PR keeps the app working while restoring use of storybook. 

The below console output give an idea of the kind of tasks that can be continued in a follow up PR: 

```WARNING in configuration
 
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
 
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
 

 
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
 
This can impact web performance.
 
Assets: 
 
  js/app.22ea031e.js (438 KiB)
 
  js/react-app.08979564.js (2.03 MiB)
 
  styles.css (11.4 MiB)
 

 
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
 
Entrypoints:
 
  styles (11.4 MiB)
 
      styles.css
 
      js/styles.a9becdc3.js
 
  app (438 KiB)
 
      js/app.22ea031e.js
 
  react-app (2.03 MiB)
 
      js/react-app.08979564.js
 

 

 
WARNING in webpack performance recommendations: 
 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
 
For more info visit https://webpack.js.org/guides/code-splitting/
 
Child mini-css-extract-plugin node_modules/css-loader/index.js??ref--4-1!node_modules/postcss-loader/src/index.js??ref--4-2!node_modules/resolve-url-loader/index.js!node_modules/sass-loader/dist/cjs.js??ref--4-4!assets/stylesheets/application.scss:
 
    Entrypoint mini-css-extract-plugin = *
 
    [1] ./node_modules/css-loader??ref--4-1!./node_modules/postcss-loader/src??ref--4-2!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--4-4!./assets/stylesheets/application.scss 11.5 MiB {0} [built]
 
    [5] ./assets/images/icon-triangle.svg 79 bytes {0} [built]
 
    [6] ./assets/images/_deprecated/search-button.png 79 bytes {0} [built]
 
    [7] ./assets/images/icon--print.png 77 bytes {0} [built]
 
    [8] ./assets/images/icon--print@2x.png 80 bytes {0} [built]
 
        + 4 hidden modules
 
```

## Test instructions

Everything should work as before. 

## Checklist

[//]: # "When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/master/docs/Code%20review%20guidelines.md"

- [ ] Has the branch been rebased to master?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or Acceptance)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, IE11, Safari)

### CODE REVIEW

**Comment by debitan** [comment]
> Do we not need UglifyJsPlugin? If we remove this we will have a larger JS dist file or am I missing something?

apparently it is the default behaviour now and not needed - https://webpack.js.org/migrate/4/#deprecatedremoved-plugins

**Comment by ian-leggett** [comment]
> > Do we not need UglifyJsPlugin? If we remove this we will have a larger JS dist file or am I missing something?
> 
> apparently it is the default behaviour now and not needed - https://webpack.js.org/migrate/4/#deprecatedremoved-plugins

Ha you just beat me to it, just read this and for prod we don't need it.

**Comment by debitan** [comment]
@ian-leggett I wouldn't have approved this just yet! haha still got a few issues to work through. Visual and functional tests are still failing. Asking for @PippoRaimondi 's help.

**Comment by debitan** [comment]
Was confused by `merge.smart` not working with the updated version of `webpack-smart`. There was no documentation around them dropping it, but found this commit that dropped it.

https://github.com/survivejs/webpack-merge/commit/1c1c2f1e4748da74854a7eec3ab5b676f56b9835

`That's too tricky to support with all the special cases. Regular merge
seems to be powerful enough in practice and it's absolutely clear what
it's doing.`

**Comment by debitan** [comment]
Reworked and put up as new separate PR

**Pull request closed without merging**
