### PR TITLE
Add notification alert icon into top header navigation

### PR DESCRIPTION
**Pull request by dredmonds**
## Description of change

Notification alert on the top navigation provides a greater visibility of notification service and provide an additional entry point to reminders page.

## Test instructions

- From Django admin, set active userFeatureFlagName into `reminder-summary`
- Navigate to Personalise Dashboard(if active), Companies, Contacts, Events, Interactions, Investments, Orders and Support
- It display a notification alert bell next into `Switch to Data Workspace` if `reminders-summary` is activated
- It shown red badge next the notification bell if having number of messages.

### Before

image

### After
**With reminders notification**
image

**No active reminders notification**
image

## Checklist

[//]: # 'When submitting a PR make sure the code review guidelines have been satisfied.
https://github.com/uktrade/data-hub-frontend/blob/main/docs/Code%20review%20guidelines.md'

- [x] Has the branch been rebased to main?
- [ ] Automated tests (Any of the following when applicable: Unit, Functional or End-to-End)
- [ ] Manual compatibility testing (Browsers: Chrome, Firefox, Edge, Safari)

### CODE REVIEW

**Comment by paulgain** [comment]
@dredmonds I've come across a few issues that need addressing. Happy to help out :smiley:.

1. The notification bell cannot be viewed on mobile (iPhone 12 or smaller) unless you expand the menu, it should sit adjacent to the menu, not within it, otherwise you have no idea you have notifications on smaller devices.
2. Ideally when the page initially loads the white bell should always be visible, once the API responds with the notification count we should then overlay the count and the red background together. Currently, when refreshing the page the “Switch to Data Workspace” snaps left when the notification count API results come back as it's only at that point you get to see the bell which is not ideal - we don't want the UI moving about.
3. Currently, when making an API call to fetch the count the `Task` component inserts a progress indicator on the page which increases the height of the Data Hub header, once the results come back the header snaps back into place, again not ideal. All we need to do is create a smaller loading indicator, here is an [example](https://github.com/uktrade/data-hub-frontend/blob/main/src/apps/investments/client/projects/create/CompanySummaryTable.jsx#L27) of one.
4. When viewing the notification bell on the dashboard, investments and support the count and red background nearly covers the bell icon, now compare that when looking at companies, contacts, events and interactions you’ll see it looks better as there is less overlap. Ideally we want consistency across Data Hub.

**Comment by paulgain** [comment]
The notification bell icon needs to be consistent.

Screenshot 2022-12-13 at 11 36 52

**Comment by dredmonds** [comment]
> 3\. example

**Comment by dredmonds** [comment]
Thanks Paul for the feedback:

1. The notification bell for mobile phone not yet implemented which another ticket being created `https://uktrade.atlassian.net/browse/RR-725`

2. Due to split mili-seconds to process a `CheckUserFeatureFlag` it causes to flicker the notification bell. Because the condition is only show the notification bell if user feature flag "reminders-summary" is on.  I'm open on any suggestion to improve this issue.

3. I take note this comment and taking an action.

4. At the moment, I can't replicate this issue. It would be great to included what browser being used and screen size.

5. I take this comment and taking an action. 


> @dredmonds I've come across a few issues that need addressing. Happy to help out 😃.
> 
> 1. The notification bell cannot be viewed on mobile (iPhone 12 or smaller) unless you expand the menu, it should sit adjacent to the menu, not within it, otherwise you have no idea you have notifications on smaller devices.
> 2. Ideally when the page initially loads the white bell should always be visible, once the API responds with the notification count we should then overlay the count and the red background together. Currently, when refreshing the page the “Switch to Data Workspace” snaps left when the notification count API results come back as it's only at that point you get to see the bell which is not ideal - we don't want the UI moving about.
> 3. Currently, when making an API call to fetch the count the `Task` component inserts a progress indicator on the page which increases the height of the Data Hub header, once the results come back the header snaps back into place, again not ideal. All we need to do is create a smaller loading indicator, here is an [example](https://github.com/uktrade/data-hub-frontend/blob/main/src/apps/investments/client/projects/create/CompanySummaryTable.jsx#L27) of one.
> 4. When viewing the notification bell on the dashboard, investments and support the count and red background nearly covers the bell icon, now compare that when looking at companies, contacts, events and interactions you’ll see it looks better as there is less overlap. Ideally we want consistency across Data Hub.
> 5. **I see you have deleted 10 Cypress visual screenshots. I think it's important we generate new visuals including the new bell icon as these visuals catch a lot of visual regressions during development.**

**Review by santoshdasa12345 — APPROVED** [review]

**Review by elcct — APPROVED** [review]

**Pull request merged**
