### PR TITLE
renamed step definitions folders with underscore to recognize feature lines

### PR DESCRIPTION
**Pull request by venureddy95**
Feature files are not recognizing the step definitions as the folder name has dash instead of an underscore. So these changes....

### CODE REVIEW

**Comment by tyom** [comment]
Can you expand on the issue of using underscores in folder names?

**Comment by yeahfro** [comment]
Unfortunately WebStorm/JetBrains does not recognise step definitions unless they are in a step_definitions folder.

**Comment by feedmypixel** [comment]
> @tyom @feedmypixel Unfortunately WebStorm/JetBrains does not recognise step definitions unless they are in a step_definitions folder. This allows the step definition to be clickable from the cucumber file.

yup confirmed, and you can't change it in `IntelliJ`

**Comment by feedmypixel** [comment]
screen shot 2017-09-21 at 15 55 59
@tyom you don't get the `ctrl` click Jazz with the folder `-` name change

**Pull request merged**
